import type { Game } from './games'

export const DEFAULT_GAMES: Game[] = [
  {
    id: 'endeavor',
    name: 'Endeavor',
    publisher: 'Endeavor Games',
    players: { min: 3, max: 5 },
    scoring_model: 'end_game',
    scoring: [
      { id: 'villes', label: 'Villes', type: 'number', confident: true },
      { id: 'routes', label: 'Routes', type: 'number', confident: true },
      { id: 'industrie', label: 'Industrie', type: 'number', confident: true },
      { id: 'culture', label: 'Culture', type: 'number', confident: true },
      { id: 'finances', label: 'Finances', type: 'number', confident: true },
      { id: 'politique', label: 'Politique', type: 'number', confident: true },
      { id: 'cartes_actifs', label: 'Cartes actifs', type: 'number', confident: true },
      { id: 'gouverneur_vide', label: 'Gouverneur vide', type: 'boolean', confident: true },
      { id: 'universites', label: 'Universités', type: 'number', confident: true },
      { id: 'population_port', label: 'Population port', type: 'number', confident: true },
      { id: 'esclavage', label: 'Esclavage', type: 'number', confident: true },
    ],
    computed: [
      { id: 'bonus_gouverneur', label: 'Bonus gouverneur', formula: 'gouverneur_vide ? 3 : 0', confident: true },
      { id: 'bonus_universites', label: 'Bonus universités', formula: 'universites * 3', confident: true },
      { id: 'bonus_population', label: 'Bonus population', formula: 'floor(population_port / 3)', confident: true },
      { id: 'total', label: 'Total', formula: 'villes + routes + industrie + culture + finances + politique + cartes_actifs + bonus_gouverneur + bonus_universites + bonus_population - esclavage', confident: true },
    ],
    validated: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'chateau-combo',
    name: 'Château Combo',
    players: { min: 2, max: 5 },
    scoring_model: 'end_game',
    scoring: [
      { id: 'carte_1_1', label: 'Carte 1-1', type: 'number', confident: true },
      { id: 'carte_1_2', label: 'Carte 1-2', type: 'number', confident: true },
      { id: 'carte_1_3', label: 'Carte 1-3', type: 'number', confident: true },
      { id: 'carte_2_1', label: 'Carte 2-1', type: 'number', confident: true },
      { id: 'carte_2_2', label: 'Carte 2-2', type: 'number', confident: true },
      { id: 'carte_2_3', label: 'Carte 2-3', type: 'number', confident: true },
      { id: 'carte_3_1', label: 'Carte 3-1', type: 'number', confident: true },
      { id: 'carte_3_2', label: 'Carte 3-2', type: 'number', confident: true },
      { id: 'carte_3_3', label: 'Carte 3-3', type: 'number', confident: true },
      { id: 'cles_restantes', label: 'Clés restantes', type: 'number', confident: true },
    ],
    computed: [
      { id: 'total', label: 'Total', formula: 'carte_1_1 + carte_1_2 + carte_1_3 + carte_2_1 + carte_2_2 + carte_2_3 + carte_3_1 + carte_3_2 + carte_3_3 + cles_restantes', confident: true },
    ],
    validated: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'nokosu-dice',
    name: 'Nokosu Dice',
    publisher: 'OKAZU Brand',
    players: { min: 2, max: 5 },
    scoring_model: 'per_round',
    rounds: { perPlayer: 1, offset: 0 },
    scoring: [
      { id: 'score', label: 'Score', type: 'number', confident: true },
    ],
    computed: [
      { id: 'total', label: 'Total', formula: 'score', confident: true },
    ],
    scoring_notes: "Chaque joueur joue une fois en tant qu'attaquant. Le nombre de manches est égal au nombre de joueurs.",
    tiebreak_description: "En cas d'égalité, le joueur ayant le plus grand chiffre sur son dernier dé lors de la dernière manche l'emporte.",
    validated: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'foret-mixte-dartmoor',
    name: 'Forêt Mixte Dartmoor',
    players: { min: 2, max: 5 },
    scoring_model: 'end_game',
    scoring: [
      { id: 'arbres', label: 'Arbres', type: 'number', confident: true },
      { id: 'landes', label: 'Landes', type: 'number', confident: true },
      { id: 'horizontal', label: 'Horizontal', type: 'number', confident: true },
      { id: 'haut', label: 'Haut', type: 'number', confident: true },
      { id: 'bas', label: 'Bas', type: 'number', confident: true },
      { id: 'grotte', label: 'Grotte', type: 'number', confident: true },
    ],
    computed: [
      { id: 'total', label: 'Total', formula: 'arbres + landes + horizontal + haut + bas + grotte', confident: true },
    ],
    validated: true,
    createdAt: '2024-01-01T00:00:00.000Z',
  },
]
